In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

client_key = ''#클라이언트 키 는 동적으로 구할 것
area_code = '41590'
date = '201709'
#공공데이터 에서 개발계정, 서비스정보에서 end point 란에서 제공하는 주소를 가져옴
url = 'http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?LAWD_CD={}&DEAL_YMD={}&serviceKey={}'.format(area_code, date, client_key)

information = []

response = requests.get(url)
soup = BeautifulSoup(response.content.decode('utf-8'), 'xml')
item_sets = soup.find_all('item')


for item_set in item_sets:
    price = item_set.find('거래금액').text
    year = item_set.find('년').text
    town = item_set.find('법정동').text
    apartment = item_set.find('아파트').text
    month = item_set.find('월').text
    day = item_set.find('일').text
    area = item_set.find('전용면적').text
    area_number = item_set.find('지번').text
    area_code = item_set.find('지역코드').text
    floor = item_set.find('층').text
    
    
    information.append([price,year,town,apartment,month,day,area,area_number,area_code,floor])

#information
info_columns = ['거래금액', '년', '법정동', '아파트', '월', '일', '전용면적', '지번', '지역코드', '층']

paper = pd.DataFrame(information, columns = info_columns)

paper

,거래금액,년,법정동,아파트,월,일,전용면적,지번,지역코드,층
0,"25,050",2017,진안동,진안골마을주공11단지,9,1~10,84.99,911,41590,5
1,"24,500",2017,진안동,월드메르디앙1단지,9,1~10,84.91,935,41590,8
2,"23,450",2017,진안동,월드메르디앙2단지,9,1~10,84.91,936,41590,5
3,"23,000",2017,진안동,월드메르디앙1단지,9,1~10,76.29,935,41590,9
4,"22,600",2017,진안동,월드메르디앙1단지,9,11~20,84.91,935,41590,2
5,"25,000",2017,진안동,진안골마을주공11단지,9,11~20,75.99,911,41590,4
6,"15,800",2017,진안동,화남(506-0),9,11~20,59.94,506,41590,10
7,"20,100",2017,진안동,화남,9,11~20,84.44,496,41590,7
8,"24,200",2017,진안동,진안골마을주공11단지,9,21~30,84.99,911,41590,1
9,"26,500",2017,진안동,진안골마을주공11단지,9,21~30,84.99,911,41590,15
10,"24,500",2017,병점동,화성병점양우내안애,9,1~10,58.33,872,41590,7
11,"19,000",2017,병점동,한신,9,1~10,59.81,485,41590,6
12,"25,300",2017,병점동,늘벗마을신창1차,9,1~10,84.93,817,41590,2
13,"23,200",2017,병점동,병점임광그대가,9,1~10,84.95,868,41590,3
14,"26,000",2017,병점동,늘벗마을신창1차,9,1~10,84.93,817,41590,2
15,"23,900",2017,병점동,늘벗마을신창1차,9,1~10,84.94,817,41590,9
16,"17,700",2017,병점동,주공1단지,9,1~10,49.95,809,41590,8
17,"24,000",2017,병점동,느치미마을주공4단지,9,1~10,75.99,859,41590,13
18,"24,000",2017,병점동,다정마을신한에스빌2차,9,1~10,84.88,867,41590,8
19,"19,850",2017,병점동,송화마을우남퍼스트빌3차,9,1~10,83.74,506,41590,9
20,"19,100",2017,병점동,송화마을우남퍼스트빌3차,9,1~10,83.74,506,41590,3
21,"18,400",2017,병점동,대창,9,1~10,59.83,359,41590,9
22,"21,000",2017,병점동,송화마을우남퍼스트빌3차,9,1~10,83.74,506,41590,7
23,"24,000",2017,병점동,남수원두산,9,1~10,84.9,282,41590,10
24,"21,800",2017,병점동,병점성호,9,1~10,84.97,500-1,41590,4
25,"23,000",2017,병점동,병점임광그대가,9,1~10,84.95,868,41590,1
26,"27,750",2017,병점동,남수원두산,9,1~10,134.97,282,41590,15
27,"26,500",2017,병점동,느치미마을주공뜨란채3단지,9,1~10,84.91,821,41590,15
28,"20,000",2017,병점동,안화동마을주공7단지,9,1~10,51.72,849,41590,5
29,"20,000",2017,병점동,신미주,9,1~10,84.79,201-2,41590,10
...,...,...,...,...,...,...,...,...,...,...
580,"20,500",2017,남양읍 신남리,기산베스트빌,9,1~10,84.99,25-9,41590,5
581,"17,700",2017,남양읍 신남리,대광파인밸리골드,9,1~10,84.31,1563,41590,2
582,"15,000",2017,남양읍 무송리,금광포란재,9,11~20,81.15,642,41590,3
583,"15,200",2017,남양읍 무송리,금광포란재,9,11~20,81.15,642,41590,7
584,"6,380",2017,매송면 원평리,유원아파트,9,1~10,66.73,78-1,41590,3
585,"13,900",2017,마도면 두곡리,백상화인빌,9,21~30,59.96,590,41590,7
586,"13,700",2017,마도면 두곡리,백상화인빌,9,21~30,59.96,590,41590,5
587,"19,500",2017,송산면 사강리,송산 렉스타운아파트,9,11~20,94.43,636-3,41590,1
588,"16,000",2017,송산면 육일리,포도마을코스코밸리,9,1~10,59.92,726,41590,10
589,"17,750",2017,송산면 육일리,포도마을코스코밸리,9,1~10,84.95,726,41590,10
590,"16,000",2017,송산면 육일리,포도마을코스코밸리,9,21~30,59.92,726,41590,6
591,"18,500",2017,송산면 육일리,포도마을코스코밸리,9,21~30,84.95,726,41590,8
592,"10,900",2017,팔탄면 가재리,진우,9,1~10,49.5,692-1,41590,3
593,"10,900",2017,팔탄면 가재리,진우,9,1~10,49.5,692-1,41590,5
594,"11,000",2017,팔탄면 가재리,진우,9,21~30,49.5,692-1,41590,12
595,"10,300",2017,팔탄면 가재리,진우,9,21~30,49.5,692-1,41590,1
596,"9,280",2017,팔탄면 가재리,진우,9,21~30,39.6,692-1,41590,10
597,"11,500",2017,장안면 사곡리,산호,9,11~20,59.88,170,41590,4
598,"11,800",2017,장안면 사곡리,산호,9,21~30,59.88,170,41590,9
599,"11,800",2017,정남면 발산리,동남훼미리,9,1~10,49.92,490-12,41590,13
600,"10,400",2017,정남면 발산리,동남훼미리,9,1~10,49.92,490-12,41590,15
601,"14,200",2017,정남면 발산리,동남훼미리,9,11~20,59.9,490-12,41590,10
602,"11,500",2017,정남면 발산리,동남훼미리,9,11~20,49.92,490-12,41590,8
603,"11,300",2017,정남면 발산리,동남훼미리,9,11~20,49.92,490-12,41590,4
604,"14,000",2017,정남면 발산리,동남훼미리,9,11~20,59.9,490-12,41590,9
605,"9,500",2017,정남면 발산리,동남훼미리,9,11~20,39.81,490-12,41590,2
606,"9,050",2017,정남면 발산리,동남훼미리,9,21~30,39.81,490-12,41590,3
607,"14,500",2017,정남면 발산리,동남훼미리,9,21~30,59.9,490-12,41590,12
608,"15,700",2017,정남면 덕절리,근형심포니,9,1~10,84.99,498,41590,5
609,"32,700",2017,동탄면 송리,동탄2하우스디더레이크,9,1~10,59.99,BL-66,41590,10